### ISSUE TITLE
update aws sdk component from aws

### ISSUE THREAD

**Issue by omansour** [M6Web/AwsBundle#28]
https://github.com/aws/aws-sdk-php/releases/tag/2.8.2

**Comment by omansour** [comment]
okay there's now: https://github.com/aws/aws-sdk-php/releases/tag/3.0.5

**Comment by b-viguier** [comment]
Won't be fixed.
This bundle is deprecated in favor of https://github.com/aws/aws-sdk-php-symfony
See #32
